version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: skillpass-postgres
    environment:
      POSTGRES_DB: skillpass_db
      POSTGRES_USER: skillpass_user
      POSTGRES_PASSWORD: skillpass_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillpass_user -d skillpass_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: skillpass-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillpass.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: 